[package]
name = "rust-grpc"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tokio-postgres = "0.7.3"
tokio = { version = "1.12.0", features = ["full"] }
tonic = "0.5"
prost = "0.8"

[build-dependencies]
tonic-build = "0.5"

